### ISSUE TITLE
From Element to Handle

### ISSUE THREAD

**Issue by thelink2012** [dcampbell24/iup-rust#17]
There is a `impl From<E: Element> for Handle` implemented _(which allows `Handle::from(elem)` and at most `elem.into()`)_ to allow a conversion between specialized objects to a basic elemental handle and there's also a `pub fn from_element<E: Element>(elem: E) -> Handle` implemented as a constructor of the `Handle` object.

**Should the `from_element` constructor be removed in favor of `From` trait?**

Note there are other from-like methods in the Element trait (Handle is also a Element), those shouldn't be _removed_ but it's good to think they exist in relation to `from_element`:
- `fn from_handle(handle: Handle) -> Result<Self, Handle>`
- `unsafe fn from_raw_unchecked(ih: *mut iup_sys::Ihandle) -> Self`
- `fn from_raw(ih: *mut iup_sys::Ihandle) -> Self`

**Comment by dcampbell24** [comment]
Yeah, not a high priority, but the From trait is now considered more idiomatic way of doing things.
