### ISSUE TITLE
Hierarchy Operations in a separate trait

### ISSUE THREAD

**Issue by thelink2012** [dcampbell24/iup-rust#20]
There are two types of elements:
- Those that are containers _(e.g. dialog, frame, hbo, vbox, etc)_ and can store other elements in it. They can have parents, childs and a brother. For instance `IupAppend` only works on those containers.
- Those that are _final_ nodes, they can have parents and a brother but cannot have childs. The container containers are a superset of this node type.

Currently all the hierarchy operations are implemented in the Element trait. **Should those prehaps be separated in two traits instead of leaving them in `Element`?**

The upside I see is that it'll be cleaner which objects are containers and which aren't.
The downsides is that `Handle` would need to implement both _(?)_ and give the doubt if the contained handle is really part of that trait.

**Comment by dcampbell24** [comment]
I don't think having to implement two traits is a huge cost, but if there start to get to be too many traits we can look at consolidating later. I am not sure what you mean by

```
 and give the doubt if the contained handle is really part of that trait.
```

**Comment by thelink2012** [comment]
Oh look, there are also the elements that do not support any hierarchical operation such as timers! So it's three kind of elements.
I guess the trait will come in hand.
