### ISSUE TITLE
IupConvertXYToPos in it's own trait or object

### ISSUE THREAD

**Issue by thelink2012** [dcampbell24/iup-rust#21]
IupConvertXYToPos  is limited to a few elements _(IupText, IupScintilla, IupList, IupTree and IupMatrix)_, it's currently implemented in the Element trait.

However it seems like a case it should be either:
- Move into a separate trait...
- or maybe add directly in the implementation of those specific controls.

Thoughts?

**Comment by dcampbell24** [comment]
I would say move into another trait, but don't have a really strong argument. What do you see as the pros and cons?

**Comment by thelink2012** [comment]
For the record there's also `IupTextConvertLinColToPos` and `IupTextConvertPosToLinCol` which are allowed only on IupText and IupScintilla. Though on Scintilla the parameter has a sightly meaning change:

> IupText auxiliary functions IupTextConvertLinColToPos and IupTextConvertPosToLinCol can also be used. But here lin and col starts at 0, pos starts at 0.
