### ISSUE TITLE
Return a dialog from the `f` closure in `with_iup`?!

### ISSUE THREAD

**Issue by thelink2012** [dcampbell24/iup-rust#22]
From [IUP docs](http://webserver2.tecgraf.puc-rio.br/iup/en/func/iupmainloop.html)

> If IupMainLoop is called without any visible dialogs and no active timers, the application will hang and will not be possible to close the main loop. The process will have to be interrupted by the system.

So we should perhaps enforce a visible dialog by making the user return a dialog (wrapped in a Result?) from the `f` closure passed to `with_iup`

Though what about this `and no active timers` parts?!?!?!! That probably means we're able to call `IupMainLoop` with no active dialogs if the user have set up a timer in `f`, how to deal with this?

**Comment by dcampbell24** [comment]
I don't think we need to protect against this, but can leave the issue open for now.
