### ISSUE TITLE
Host docs somewhere

### ISSUE THREAD

**Issue by thelink2012** [dcampbell24/iup-rust#25]
Make `.travis.yml` publish the result of `cargo doc` somewhere. I **don't** recommend to host the docs on rust-ci as the documentation gets outdated on it due to hansjorg/rust-ci#22.

Instead, host it in ghpages of the project by using `ghp-import`. See how the hyper project does it [here](https://github.com/hyperium/hyper/blob/master/.travis.yml).

**Comment by thelink2012** [comment]
cc @dcampbell24

**Comment by dcampbell24** [comment]
Done.
