### ISSUE TITLE
error: unresolved name iup::label

### ISSUE THREAD

**Issue by planmac** [dcampbell24/iup-rust#28]
None of the examples build:
Cargo.toml
    [dependencies.iup]
    git = "https://github.com/dcampbell24/iup-rust"

main.rs = hello0.rs or hello1.rs

**Comment by thelink2012** [comment]
There is no `iup::label` anymore but `iup::control::Label`. You seem to be under the legacy API? Try `cargo update -p iup` to go to the latest version.

**Comment by planmac** [comment]
You are right! Sorry for the newby error - still not sure how that happened but all good now!
