### ISSUE TITLE
The Object Model

### ISSUE THREAD

**Issue by thelink2012** [dcampbell24/iup-rust#6]
A step to the a high-level binding is to decide the object model to be used, each has pros and cons, mainly because of the C model used in IUP.

**Note:** The pros and cons lists are not exhaustive, please consider adding more if any comes to mind. 

**Terminology:**
- _string attributes_: Using `IupGetAttribute` and `IupSetAttribute` which gets and sets a string instead of a well specified object type.
- _function/methods for attributes_: Using a function/method for each attribute, giving more type safety to it since each of those functions will set/get the correct type of the attribute instead of a string.
### Ihandle and Functions _(using string attributes)_

This is the current model in the library, all the IUP objects are described with a `Ihandle` structure and passed to functions as the first argument.

Pros:
- Simple model.
- Maps 1:1 to IUP documentation

Cons:
- Attributes aren't type-safe.
- Not possible to find out about attributes by using auto-completion.
- Annoying `&mut handle` on each function call.
### Ihandle and Functions _(using functions for attributes)_

Pros
- Simple model.
- Maps almost 1:1 to IUP documentation.
- Type-safe attributes.
- Possible to find out about attributes by using auto-completion.

Cons:
- Annoying `&mut handle` on each function call.
### Ihandle and Methods

Mirror **Ihandle and Functions _(using string attributes)_** and **Ihandle and Functions _(using functions for attributes)_** here by excluding the _**Annoying `&mut handle` on each function call**_ cons.
### Structs/Traits and Methods  _(using methods for attributes)_

Pros:
- More Rusty
- Very type-safe.
- Possible to find out about attributes by using auto-completion + only the attributes and callbacks that applies to this object in question.

Cons:
-  Complex model.
- Does not map 1:1 to IUP documentation.

Issues:
- How to deal with functions that returns a handle to any kind of object (e.g. `IupGetHandle`)?

**Comment by thelink2012** [comment]
Thoughts @dcampbell24?

**EDIT:**
Oh, the callbacks system don't work very well either using the Ihandle methodology.
For instance IupText action callback receives `(Ihandle *ih, int c, char *new_value)` meanwhile the button action callback receives `(Ihandle* ih)`.

I was very neutral + a little bit inclined to the Ihandle model, but now I think the struct/trait model is the way to go.

**Comment by dcampbell24** [comment]
I like the struct / trait approach even though I think it will require more work to implement. Unfortunately, I am probably not going to have very much free time for a while to help with this.
